#!/usr/bin/env node
/**
 * Interactive Setup Script
 * Helps configure environment files for deployment
 */

const fs = require('fs');
const path = require('path');
const readline = require('readline');
const { ethers } = require('ethers');

const PROJECT_ROOT = path.join(__dirname, '../..');
const PROJECT_DIR = path.join(__dirname, '..');
const SCRIPTS_DIR = path.join(PROJECT_ROOT, 'scripts');

const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});

function question(prompt) {
    return new Promise(resolve => rl.question(prompt, resolve));
}

async function main() {
    console.log('═'.repeat(60));
    console.log('🔧 EMBODIED CARBON LEDGER - SETUP');
    console.log('═'.repeat(60));
    console.log();

    // Check Ganache
    console.log('Checking Ganache connection...');
    const rpcUrl = 'http://127.0.0.1:7545';
    let provider;
    let accounts = [];
    
    try {
        provider = new ethers.JsonRpcProvider(rpcUrl);
        accounts = await provider.send('eth_accounts', []);
        console.log(`✅ Connected to Ganache (${accounts.length} accounts available)`);
    } catch (err) {
        console.log('⚠️  Ganache not running. Please start it first.');
        console.log('   Download: https://trufflesuite.com/ganache/');
    }

    console.log();

    // Show available accounts
    if (accounts.length > 0) {
        console.log('Available Ganache Accounts:');
        console.log('─'.repeat(60));
        for (let i = 0; i < Math.min(accounts.length, 5); i++) {
            const balance = await provider.getBalance(accounts[i]);
            const balanceEth = ethers.formatEther(balance);
            console.log(`  ${i + 1}. ${accounts[i]}`);
            console.log(`     Balance: ${balanceEth} ETH`);
        }
        console.log('─'.repeat(60));
        console.log();
        console.log('💡 TIP: In Ganache, click the 🔑 key icon next to an account');
        console.log('   to see its private key.');
        console.log();
    }

    // Get configuration from user
    console.log('Please provide the following information:');
    console.log('(Press Enter to use defaults shown in brackets)');
    console.log();

    const senderAddress = await question(
        `Sender Address [${accounts[0] || 'none'}]: `
    ) || accounts[0] || '';

    const privateKey = await question(
        'Private Key (from Ganache): '
    ) || '';

    // Validate inputs
    if (!senderAddress) {
        console.log('\n⚠️  No sender address provided.');
        rl.close();
        return;
    }

    if (!privateKey) {
        console.log('\n⚠️  No private key provided.');
        console.log('   You can add it later to scripts/.env');
    }

    // Validate private key format
    if (privateKey) {
        const keyToValidate = privateKey.startsWith('0x') ? privateKey : `0x${privateKey}`;
        try {
            const wallet = new ethers.Wallet(keyToValidate);
            if (wallet.address.toLowerCase() !== senderAddress.toLowerCase()) {
                console.log('\n⚠️  WARNING: Private key does not match sender address!');
                console.log(`   Key belongs to: ${wallet.address}`);
            }
        } catch (err) {
            console.log('\n⚠️  Invalid private key format');
        }
    }

    // Create/Update scripts/.env
    console.log('\n📝 Creating configuration files...');
    
    const scriptsEnvPath = path.join(SCRIPTS_DIR, '.env');
    const scriptsEnvContent = `# Web3 Bridge Script Configuration
# Auto-generated by setup script

# Ethereum Node
ETHEREUM_PROVIDER_URL=${rpcUrl}

# Contract (will be set after deployment)
CONTRACT_ADDRESS=

# Account Configuration
SENDER_ADDRESS=${senderAddress}
PRIVATE_KEY=${privateKey.startsWith('0x') ? privateKey : (privateKey ? '0x' + privateKey : '')}

# Other Settings
CONTRACT_ABI_PATH=contract_abi.json
GAS_PRICE_GWEI=10
`;

    fs.writeFileSync(scriptsEnvPath, scriptsEnvContent);
    console.log(`   ✅ Created: scripts/.env`);

    // Create project/.env
    const projectEnvPath = path.join(PROJECT_DIR, '.env');
    const projectEnvContent = `# Frontend Environment Configuration
# Auto-generated by setup script

# Contract (will be set after deployment)
VITE_CONTRACT_ADDRESS=

# Network
VITE_NETWORK_ID=5777
VITE_ETHEREUM_PROVIDER_URL=${rpcUrl}

# Deployment (optional - uses Ganache account if not set)
DEPLOYER_PRIVATE_KEY=${privateKey.startsWith('0x') ? privateKey : (privateKey ? '0x' + privateKey : '')}
`;

    fs.writeFileSync(projectEnvPath, projectEnvContent);
    console.log(`   ✅ Created: project/.env`);

    // Create output directory
    const outputDir = path.join(PROJECT_ROOT, 'output');
    if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
        console.log(`   ✅ Created: output/`);
    }

    console.log();
    console.log('═'.repeat(60));
    console.log('✅ SETUP COMPLETE!');
    console.log('═'.repeat(60));
    console.log();
    console.log('Next Steps:');
    console.log('  1. Start Ganache (if not already running)');
    console.log('  2. Run deployment: npm run deploy');
    console.log('     Or use: ..\\deploy.bat (from project root)');
    console.log();
    
    const deploy = await question('Deploy now? (y/N): ');
    if (deploy.toLowerCase() === 'y') {
        console.log('\nStarting deployment...\n');
        rl.close();
        require('./deploy.js');
    } else {
        console.log('\nRun "npm run deploy" when ready.');
        rl.close();
    }
}

main().catch(err => {
    console.error('Setup failed:', err.message);
    rl.close();
    process.exit(1);
});

